### ISSUE TITLE
Flavor composer instead of symfony ?

### ISSUE THREAD

**Issue by tristanbes** [platformsh/platformsh-example-symfony#15]
Hi, 

Why in the 3.0 branch, you have `flavor: composer` instead of `flavor : symfony` ?
https://github.com/platformsh/platformsh-example-symfony/blob/3.0/.platform.app.yaml#L10

Thanks

**Comment by JGrubb** [comment]
Hi @tristanbes - `symfony` is an alias of `composer`.  This is confusing IMO, but that's the deal.

**Comment by tristanbes** [comment]
Imo there's not point of keeping an alias if it does nothing more, it adds confusion and noise like i just created ;-)

Thanks for the answer

**Comment by JGrubb** [comment]
I totally agree.  I was about to say that that option is deprecated and that we're going to scrub it out of all our documentation, but I wanted to confirm first.
